version: "3.8"

services:
  grades-app:
    image: nefnief1/grades-app:latest
    platform: linux/amd64 # Changed back to AMD64 to match existing image
    container_name: grades-application
    ports:
      - "8080:8080" # Assuming the app runs on port 8080, adjust as needed
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Load from .env file by default, but also allow direct environment variable overrides
      - NEXT_PUBLIC_APPWRITE_ENDPOINT=${NEXT_PUBLIC_APPWRITE_ENDPOINT}
      - NEXT_PUBLIC_APPWRITE_PROJECT_ID=${NEXT_PUBLIC_APPWRITE_PROJECT_ID}
      - NEXT_PUBLIC_APPWRITE_DATABASE_ID=${NEXT_PUBLIC_APPWRITE_DATABASE_ID}
      - NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_USERS_COLLECTION_ID}
      - NEXT_PUBLIC_APPWRITE_SUBJECTS_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_SUBJECTS_COLLECTION_ID}
      - NEXT_PUBLIC_APPWRITE_GRADES_COLLECTION_ID=${NEXT_PUBLIC_APPWRITE_GRADES_COLLECTION_ID}
      # For testing without Appwrite connection
      - NEXT_PUBLIC_FORCE_LOCAL_MODE=${NEXT_PUBLIC_FORCE_LOCAL_MODE:-false}
    volumes:
      - grades_data:/app/data # For data persistence
    networks:
      - grades_network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  grades_network:
    driver: bridge

volumes:
  grades_data:
    driver: local
