[phases.setup]
nixPkgs = ['nodejs_20', 'openssl', 'gcc', 'python3']
cmds = [
  'echo "Node version before setup: $(node --version)"',
  'export PATH="/nix/store/$(ls -t /nix/store | grep -m 1 nodejs | head -1)/bin:$PATH"',
  'npm config set prefix "/usr/local"',
  'npm install -g pnpm n',
  'n 20.10.0',
  'export PATH="/usr/local/bin:$PATH"',
  'echo "Node version after setup: $(node --version)"'
]

[phases.install]
cmds = ['node -v && npm install -g pnpm && pnpm install']

[phases.build]
cmds = ['pnpm build']

[variables]
NODE_OPTIONS = '--max-old-space-size=4096'

[start]
cmd = 'pnpm start'
