[phases.setup]
nixPkgs = ["nginx"]

[phases.install]
# No npm install needed for static files
cmds = ["echo 'No installation required for static files'"]

[phases.build]
# Skip build phase - using prebuilt files
cmds = ["echo 'Using prebuilt static files from out directory'"]

[variables]
NODE_OPTIONS = '--max-old-space-size=4096'
NIXPACKS_METADATA = "static-site"
PORT = "80"

[start]
cmd = "nginx -g 'daemon off;'"

[staticAssets]
# Serve the out directory as static assets
"out" = "/"
