[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railpack"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "3000"
