name: Deploy Prebuilt Site

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
      - 'out/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check if out directory exists
      run: |
        if [ ! -d "out" ]; then
          echo "Error: out directory not found. Please build locally first with 'npm run build'"
          exit 1
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        cname: grades.nief.tech
